/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gudang;

import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author LENOVO
 */
public class tambahdatabm extends javax.swing.JFrame {
    private DefaultTableModel model=null;
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k = new koneksi();

    /**
     * Creates new form tambahdatabarang
     */
    public tambahdatabm() {
        initComponents();
        k.connect();
        refreshTable();
        refreshCombo();
    }
    
    class brg_masuk extends tambahdatabm{
            int id_bm, id_brg, jumlah;
            String tanggal;
            
            public brg_masuk() {
                String combo = boxidbarang.getSelectedItem().toString();
                String[] arr = combo.split(":");
                this.id_brg = Integer.parseInt(arr[0]);
                try {
                    Date date = texttanggalbm.getDate();
                    DateFormat dateformat = new SimpleDateFormat ("YYYY-MM-dd");
                    this.tanggal = dateformat.format(date);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
                this.jumlah = Integer.parseInt(textjumlahbm.getText());
            }
        }
    
        public void refreshTable(){
        model = new DefaultTableModel();
        model.addColumn("id bm");
        model.addColumn("id brg");
        model.addColumn("jumlah");
        model.addColumn("tanggal");
        tablebm.setModel(model);
        try {
            this.stat = k.getCon().prepareStatement("select * from brg_masuk ");
            this.rs = this.stat.executeQuery();
            while (rs.next()) {
                Object[] data = {
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4)
                };
                model.addRow(data); 
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        textidbm.setText("");
        textjumlahbm.setText("");
    }
        public void refreshCombo(){
            try {
                    this.stat = k.getCon().prepareStatement("select * from barang ");
                    this.rs = this.stat.executeQuery();
                   while (rs.next()) {
                       boxidbarang.addItem(rs.getString("id_brg")+":"+
                       rs.getString("nama_barang")+":"+rs.getString("kode_barang")+":"+rs.getString("stok"));
                   }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        namabm = new javax.swing.JLabel();
        textidbm = new javax.swing.JTextField();
        jenisbm = new javax.swing.JLabel();
        jumlahbm = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablebm = new javax.swing.JTable();
        tombolinputbm = new javax.swing.JButton();
        tombolupdatebm = new javax.swing.JButton();
        tomboldeletebm = new javax.swing.JButton();
        tanggalbm = new javax.swing.JLabel();
        tombolbarang = new javax.swing.JButton();
        tombolbk = new javax.swing.JButton();
        logoutbm = new javax.swing.JButton();
        textjumlahbm = new javax.swing.JTextField();
        texttanggalbm = new com.toedter.calendar.JDateChooser();
        tombolbr = new javax.swing.JButton();
        boxidbarang = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("TAMBAH LIST DATA BARANG MASUK");

        namabm.setText("id barang masuk");

        textidbm.setEnabled(false);
        textidbm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textidbmActionPerformed(evt);
            }
        });

        jenisbm.setText("id barang");

        jumlahbm.setText("Jumlah");

        tablebm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablebm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablebmMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablebm);

        tombolinputbm.setText("INPUT");
        tombolinputbm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolinputbmActionPerformed(evt);
            }
        });

        tombolupdatebm.setText("UPDATE");
        tombolupdatebm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolupdatebmActionPerformed(evt);
            }
        });

        tomboldeletebm.setText("DELETE");
        tomboldeletebm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomboldeletebmActionPerformed(evt);
            }
        });

        tanggalbm.setText("Tanggal");

        tombolbarang.setText("Barang");
        tombolbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolbarangActionPerformed(evt);
            }
        });

        tombolbk.setText("Barang keluar");
        tombolbk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolbkActionPerformed(evt);
            }
        });

        logoutbm.setText("Logout");
        logoutbm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbmActionPerformed(evt);
            }
        });

        textjumlahbm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textjumlahbmActionPerformed(evt);
            }
        });

        tombolbr.setText("Barang rusak");
        tombolbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolbrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutbm, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jumlahbm)
                                    .addComponent(jenisbm)
                                    .addComponent(tanggalbm, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(texttanggalbm, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textjumlahbm, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tombolinputbm)
                                .addGap(45, 45, 45)
                                .addComponent(tombolupdatebm)
                                .addGap(31, 31, 31)
                                .addComponent(tomboldeletebm)))
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tombolbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(tombolbk, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(tombolbr, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(namabm)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(textidbm, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                                        .addComponent(boxidbarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logoutbm, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namabm)
                    .addComponent(textidbm, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jenisbm))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxidbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jumlahbm)
                    .addComponent(textjumlahbm, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggalbm)
                    .addComponent(texttanggalbm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolinputbm)
                    .addComponent(tombolupdatebm)
                    .addComponent(tomboldeletebm))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolbarang)
                    .addComponent(tombolbk)
                    .addComponent(tombolbr))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textidbmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textidbmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textidbmActionPerformed

    private void tombolinputbmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolinputbmActionPerformed
        // TODO add your handling code here:
         try {
            brg_masuk barm = new brg_masuk();
            this.stat = k.getCon().prepareStatement("Insert into brg_masuk values(?,?,?,?)");
            this.stat.setInt(1, 0);
            this.stat.setInt(2, barm.id_brg);
            this.stat.setInt(3, barm.jumlah);
            this.stat.setString(4, barm.tanggal);
            this.stat.executeUpdate();
            refreshTable();
    } catch (Exception e) {
    JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_tombolinputbmActionPerformed

    private void tombolupdatebmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolupdatebmActionPerformed
        // TODO add your handling code here:
          try {
            brg_masuk barm = new brg_masuk();
            this.stat =  k.getCon().prepareStatement("update brg_masuk set id_brg=?,"
                    + "jumlah=?,tanggal=?" + "where id_bm=?");
            stat.setInt(1, barm.id_brg);
            stat.setInt(2, barm.jumlah);
            stat.setString(3, barm.tanggal);
            stat.setString(4, textidbm.getText());
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_tombolupdatebmActionPerformed

    private void tomboldeletebmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomboldeletebmActionPerformed
        // TODO add your handling code here:
        try {
            brg_masuk barm = new brg_masuk();
            this.stat = k.getCon().prepareStatement("delete from brg_masuk where id_bm=?");
            stat.setString(1, textidbm.getText());
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_tomboldeletebmActionPerformed

    private void textjumlahbmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textjumlahbmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textjumlahbmActionPerformed

    private void logoutbmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbmActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutbmActionPerformed

    private void tombolbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolbarangActionPerformed
        // TODO add your handling code here:
        tambahdatabarang reg = new tambahdatabarang();
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tombolbarangActionPerformed

    private void tablebmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablebmMouseClicked
        // TODO add your handling code here:
        textidbm.setText(model.getValueAt(tablebm.getSelectedRow(), 0).toString());
        textjumlahbm.setText(model.getValueAt(tablebm.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_tablebmMouseClicked

    private void tombolbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolbrActionPerformed
        // TODO add your handling code here:
        tambahdatabr reg = new tambahdatabr();
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tombolbrActionPerformed

    private void tombolbkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolbkActionPerformed
        // TODO add your handling code here:
        tambahdatabk reg = new tambahdatabk();
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tombolbkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahdatabm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahdatabm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahdatabm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahdatabm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambahdatabm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxidbarang;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jenisbm;
    private javax.swing.JLabel jumlahbm;
    private javax.swing.JButton logoutbm;
    private javax.swing.JLabel namabm;
    private javax.swing.JTable tablebm;
    private javax.swing.JLabel tanggalbm;
    private javax.swing.JTextField textidbm;
    private javax.swing.JTextField textjumlahbm;
    private com.toedter.calendar.JDateChooser texttanggalbm;
    private javax.swing.JButton tombolbarang;
    private javax.swing.JButton tombolbk;
    private javax.swing.JButton tombolbr;
    private javax.swing.JButton tomboldeletebm;
    private javax.swing.JButton tombolinputbm;
    private javax.swing.JButton tombolupdatebm;
    // End of variables declaration//GEN-END:variables
}
