/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gudang;

import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author LENOVO
 */
public class tambahdatabk extends javax.swing.JFrame {
    private DefaultTableModel model=null;
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k = new koneksi();

    /**
     * Creates new form tambahdatabarang
     */
    public tambahdatabk() {
        initComponents();
        k.connect();
        refreshTable();
        refreshCombo();
    }
    
    class brg_keluar extends tambahdatabk{
            int id_bk, id_bm, jumlah;
            String tanggal;
            
            public brg_keluar() {
                String combo = boxidbm.getSelectedItem().toString();
                String[] arr = combo.split(":");
                this.id_bm = Integer.parseInt(arr[0]);
                try {
                    Date date = texttanggalbk.getDate();
                    DateFormat dateformat = new SimpleDateFormat ("YYYY-MM-dd");
                    this.tanggal = dateformat.format(date);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
                this.jumlah = Integer.parseInt(textjumlahbk.getText());
            }
        }
    
        public void refreshTable(){
        model = new DefaultTableModel();
        model.addColumn("id bk");
        model.addColumn("id bm");
        model.addColumn("jumlah");
        model.addColumn("tanggal");
        tablebk.setModel(model);
        try {
            this.stat = k.getCon().prepareStatement("select * from brg_keluar ");
            this.rs = this.stat.executeQuery();
            while (rs.next()) {
                Object[] data={
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4)
                };
                model.addRow(data); 
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        textidbk.setText("");
        textjumlahbk.setText("");
    }
        public void refreshCombo(){
            try {
                    this.stat = k.getCon().prepareStatement("select * from brg_masuk ");
                    this.rs = this.stat.executeQuery();
                   while (rs.next()) {
                       boxidbm.addItem(rs.getString("id_bm")+":"+
                       rs.getString("id_brg")+":"+rs.getString("jumlah")+":"+rs.getString("tanggal"));
                   }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        namabm = new javax.swing.JLabel();
        textidbk = new javax.swing.JTextField();
        jenisbm = new javax.swing.JLabel();
        jumlahbm = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablebk = new javax.swing.JTable();
        tombolinputbk = new javax.swing.JButton();
        tombolupdatebk = new javax.swing.JButton();
        tomboldeletebk = new javax.swing.JButton();
        tanggalbm = new javax.swing.JLabel();
        tombolbarang = new javax.swing.JButton();
        tombolbm = new javax.swing.JButton();
        logoutbk = new javax.swing.JButton();
        textjumlahbk = new javax.swing.JTextField();
        texttanggalbk = new com.toedter.calendar.JDateChooser();
        tombolbr = new javax.swing.JButton();
        boxidbm = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("TAMBAH LIST DATA BARANG KELUAR");

        namabm.setText("id barang keluar");

        textidbk.setEnabled(false);
        textidbk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textidbkActionPerformed(evt);
            }
        });

        jenisbm.setText("id barang masuk");

        jumlahbm.setText("Jumlah");

        tablebk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablebk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablebkMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablebk);

        tombolinputbk.setText("INPUT");
        tombolinputbk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolinputbkActionPerformed(evt);
            }
        });

        tombolupdatebk.setText("UPDATE");
        tombolupdatebk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolupdatebkActionPerformed(evt);
            }
        });

        tomboldeletebk.setText("DELETE");
        tomboldeletebk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomboldeletebkActionPerformed(evt);
            }
        });

        tanggalbm.setText("Tanggal");

        tombolbarang.setText("Barang");
        tombolbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolbarangActionPerformed(evt);
            }
        });

        tombolbm.setText("Barang masuk");
        tombolbm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolbmActionPerformed(evt);
            }
        });

        logoutbk.setText("Logout");
        logoutbk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbkActionPerformed(evt);
            }
        });

        textjumlahbk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textjumlahbkActionPerformed(evt);
            }
        });

        tombolbr.setText("Barang rusak");
        tombolbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolbrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(namabm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textidbk, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jumlahbm)
                                            .addComponent(jenisbm)
                                            .addComponent(tanggalbm, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(texttanggalbk, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textjumlahbk, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                                            .addComponent(boxidbm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tombolinputbk)
                                        .addGap(71, 71, 71)
                                        .addComponent(tombolupdatebk)
                                        .addGap(66, 66, 66)
                                        .addComponent(tomboldeletebk))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(tombolbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(30, 30, 30)
                                            .addComponent(tombolbm, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(31, 31, 31)
                                            .addComponent(tombolbr, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutbk, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logoutbk, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namabm)
                    .addComponent(textidbk, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jenisbm))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(boxidbm, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jumlahbm)
                    .addComponent(textjumlahbk, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggalbm)
                    .addComponent(texttanggalbk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolinputbk)
                    .addComponent(tombolupdatebk)
                    .addComponent(tomboldeletebk))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolbarang)
                    .addComponent(tombolbm)
                    .addComponent(tombolbr))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textidbkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textidbkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textidbkActionPerformed

    private void tombolinputbkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolinputbkActionPerformed
        // TODO add your handling code here:
        try {
            brg_keluar bark = new brg_keluar();
            this.stat = k.getCon().prepareStatement("Insert into brg_keluar values(?,?,?,?)");
            this.stat.setInt(1, 0);
            this.stat.setInt(2, bark.id_bm);
            this.stat.setInt(3, bark.jumlah);
            this.stat.setString(4, bark.tanggal);
            this.stat.executeUpdate();
            refreshTable();
    } catch (Exception e) {
    JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_tombolinputbkActionPerformed

    private void tombolupdatebkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolupdatebkActionPerformed
        // TODO add your handling code here:
        try {
            brg_keluar bark = new brg_keluar();
            this.stat =  k.getCon().prepareStatement("update brg_keluar set id_bm=?,"
                    + "jumlah=?,tanggal=? where id_bk=?");
            stat.setInt(1, bark.id_bm);
            stat.setInt(2, bark.jumlah);
            stat.setString(3, bark.tanggal);
            stat.setString(4, textidbk.getText());
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_tombolupdatebkActionPerformed

    private void tomboldeletebkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomboldeletebkActionPerformed
        // TODO add your handling code here:
        try {
            brg_keluar bark = new brg_keluar();
            this.stat = k.getCon().prepareStatement("delete from brg_keluar where id_bk=?");
            stat.setString(1, textidbk.getText());
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_tomboldeletebkActionPerformed

    private void textjumlahbkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textjumlahbkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textjumlahbkActionPerformed

    private void logoutbkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbkActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutbkActionPerformed

    private void tombolbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolbarangActionPerformed
        // TODO add your handling code here:
        tambahdatabarang reg = new tambahdatabarang();
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tombolbarangActionPerformed

    private void tombolbmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolbmActionPerformed
        // TODO add your handling code here:
        tambahdatabm reg = new tambahdatabm();
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tombolbmActionPerformed

    private void tombolbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolbrActionPerformed
        // TODO add your handling code here:
        tambahdatabr reg = new tambahdatabr();
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tombolbrActionPerformed

    private void tablebkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablebkMouseClicked
        // TODO add your handling code here:
        textidbk.setText(model.getValueAt(tablebk.getSelectedRow(), 0).toString());
        textjumlahbk.setText(model.getValueAt(tablebk.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_tablebkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahdatabk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahdatabk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahdatabk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahdatabk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambahdatabk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxidbm;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jenisbm;
    private javax.swing.JLabel jumlahbm;
    private javax.swing.JButton logoutbk;
    private javax.swing.JLabel namabm;
    private javax.swing.JTable tablebk;
    private javax.swing.JLabel tanggalbm;
    private javax.swing.JTextField textidbk;
    private javax.swing.JTextField textjumlahbk;
    private com.toedter.calendar.JDateChooser texttanggalbk;
    private javax.swing.JButton tombolbarang;
    private javax.swing.JButton tombolbm;
    private javax.swing.JButton tombolbr;
    private javax.swing.JButton tomboldeletebk;
    private javax.swing.JButton tombolinputbk;
    private javax.swing.JButton tombolupdatebk;
    // End of variables declaration//GEN-END:variables
}
