/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gudang;


import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author LENOVO
 */
public class tambahdatabr extends javax.swing.JFrame {
    private DefaultTableModel model=null;
    private PreparedStatement stat;
    private ResultSet rs;
    koneksi k = new koneksi();

    /**
     * Creates new form tambahdatabarang
     */
    public tambahdatabr() {
        initComponents();
        k.connect();
        refreshTable();
        refreshCombo();
    }
    
    class brg_rusak extends tambahdatabr{
            int id_br, id_bk, jumlah;
            String tanggal;
            
            public brg_rusak() {
                String combo = boxidbk.getSelectedItem().toString();
                String[] arr = combo.split(":");
                this.id_bk = Integer.parseInt(arr[0]);
                try {
                    Date date = texttanggalbr.getDate();
                    DateFormat dateformat = new SimpleDateFormat ("YYYY-MM-dd");
                    this.tanggal = dateformat.format(date);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
                this.jumlah = Integer.parseInt(textjumlahbr.getText());
            }
        }
    
        public void refreshTable(){
        model = new DefaultTableModel();
        model.addColumn("id br");
        model.addColumn("id bk");
        model.addColumn("jumlah");
        model.addColumn("tanggal");
        tablebr.setModel(model);
        try {
            this.stat = k.getCon().prepareStatement("select * from brg_rusak ");
            this.rs = this.stat.executeQuery();
            while (rs.next()) {
                Object[] data = {
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4)
                };
                model.addRow(data); 
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        textidbr.setText("");
        textjumlahbr.setText("");
    }
        public void refreshCombo(){
            try {
                    this.stat = k.getCon().prepareStatement("select * from brg_keluar ");
                    this.rs = this.stat.executeQuery();
                   while (rs.next()) {
                       boxidbk.addItem(rs.getString("id_bk")+":"+
                       rs.getString("id_bm")+":"+rs.getString("jumlah")+":"+rs.getString("tanggal"));
                   }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        namabm = new javax.swing.JLabel();
        textidbr = new javax.swing.JTextField();
        jenisbm = new javax.swing.JLabel();
        jumlahbm = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablebr = new javax.swing.JTable();
        tombolinputbr = new javax.swing.JButton();
        tombolupdatebr = new javax.swing.JButton();
        tomboldeletebr = new javax.swing.JButton();
        tanggalbm = new javax.swing.JLabel();
        tombolbarang = new javax.swing.JButton();
        tombolbk = new javax.swing.JButton();
        logoutbr = new javax.swing.JButton();
        textjumlahbr = new javax.swing.JTextField();
        texttanggalbr = new com.toedter.calendar.JDateChooser();
        tombolbm = new javax.swing.JButton();
        boxidbk = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("TAMBAH LIST DATA BARANG RUSAK");

        namabm.setText("id barang rusak");

        textidbr.setEnabled(false);
        textidbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textidbrActionPerformed(evt);
            }
        });

        jenisbm.setText("id barang keluar");

        jumlahbm.setText("Jumlah");

        tablebr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablebr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablebrMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablebr);

        tombolinputbr.setText("INPUT");
        tombolinputbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolinputbrActionPerformed(evt);
            }
        });

        tombolupdatebr.setText("UPDATE");
        tombolupdatebr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolupdatebrActionPerformed(evt);
            }
        });

        tomboldeletebr.setText("DELETE");
        tomboldeletebr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomboldeletebrActionPerformed(evt);
            }
        });

        tanggalbm.setText("Tanggal");

        tombolbarang.setText("Barang");
        tombolbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolbarangActionPerformed(evt);
            }
        });

        tombolbk.setText("Barang keluar");
        tombolbk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolbkActionPerformed(evt);
            }
        });

        logoutbr.setText("Logout");
        logoutbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbrActionPerformed(evt);
            }
        });

        textjumlahbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textjumlahbrActionPerformed(evt);
            }
        });

        tombolbm.setText("Barang masuk");
        tombolbm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolbmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(namabm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textidbr, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jumlahbm)
                                            .addComponent(jenisbm)
                                            .addComponent(tanggalbm, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(texttanggalbr, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textjumlahbr, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                                            .addComponent(boxidbk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tombolinputbr)
                                        .addGap(45, 45, 45)
                                        .addComponent(tombolupdatebr)
                                        .addGap(31, 31, 31)
                                        .addComponent(tomboldeletebr))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(tombolbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(30, 30, 30)
                                            .addComponent(tombolbk, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(31, 31, 31)
                                            .addComponent(tombolbm, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 2, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutbr, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logoutbr, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namabm)
                    .addComponent(textidbr, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisbm)
                    .addComponent(boxidbk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jumlahbm)
                    .addComponent(textjumlahbr, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggalbm)
                    .addComponent(texttanggalbr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolinputbr)
                    .addComponent(tombolupdatebr)
                    .addComponent(tomboldeletebr))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolbarang)
                    .addComponent(tombolbk)
                    .addComponent(tombolbm))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textidbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textidbrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textidbrActionPerformed

    private void tombolinputbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolinputbrActionPerformed
        // TODO add your handling code here:
         try {
            brg_rusak barr = new brg_rusak();
            this.stat = k.getCon().prepareStatement("Insert into brg_rusak values(?,?,?,?)");
            this.stat.setInt(1, 0);
            this.stat.setInt(2, barr.id_bk);
            this.stat.setInt(3, barr.jumlah);
            this.stat.setString(4, barr.tanggal);
            this.stat.executeUpdate();
            refreshTable();
    } catch (Exception e) {
    JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_tombolinputbrActionPerformed

    private void tombolupdatebrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolupdatebrActionPerformed
        // TODO add your handling code here:
         try {
            brg_rusak barr = new brg_rusak();
            this.stat =  k.getCon().prepareStatement("update brg_rusak set id_bk=?,"
                    + "jumlah=?,tanggal=?" + "where id_br=?");
            stat.setInt(1, barr.id_bk);
            stat.setInt(2, barr.jumlah);
            stat.setString(3, barr.tanggal);
            stat.setString(4, textidbr.getText());
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_tombolupdatebrActionPerformed

    private void tomboldeletebrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomboldeletebrActionPerformed
        // TODO add your handling code here:
         try {
            brg_rusak barr = new brg_rusak();
            this.stat = k.getCon().prepareStatement("delete from brg_rusak where id_br=?");
            stat.setString(1, textidbr.getText());
            stat.executeUpdate();
            refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_tomboldeletebrActionPerformed

    private void textjumlahbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textjumlahbrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textjumlahbrActionPerformed

    private void logoutbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbrActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutbrActionPerformed

    private void tablebrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablebrMouseClicked
        // TODO add your handling code here:
        textidbr.setText(model.getValueAt(tablebr.getSelectedRow(), 0).toString());
        textjumlahbr.setText(model.getValueAt(tablebr.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_tablebrMouseClicked

    private void tombolbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolbarangActionPerformed
        // TODO add your handling code here:
        tambahdatabarang reg = new tambahdatabarang();
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tombolbarangActionPerformed

    private void tombolbkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolbkActionPerformed
        // TODO add your handling code here:
        tambahdatabk reg = new tambahdatabk();
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tombolbkActionPerformed

    private void tombolbmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolbmActionPerformed
        // TODO add your handling code here:
        tambahdatabm reg = new tambahdatabm();
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tombolbmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahdatabr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahdatabr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahdatabr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahdatabr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambahdatabr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxidbk;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jenisbm;
    private javax.swing.JLabel jumlahbm;
    private javax.swing.JButton logoutbr;
    private javax.swing.JLabel namabm;
    private javax.swing.JTable tablebr;
    private javax.swing.JLabel tanggalbm;
    private javax.swing.JTextField textidbr;
    private javax.swing.JTextField textjumlahbr;
    private com.toedter.calendar.JDateChooser texttanggalbr;
    private javax.swing.JButton tombolbarang;
    private javax.swing.JButton tombolbk;
    private javax.swing.JButton tombolbm;
    private javax.swing.JButton tomboldeletebr;
    private javax.swing.JButton tombolinputbr;
    private javax.swing.JButton tombolupdatebr;
    // End of variables declaration//GEN-END:variables
}
